Form components
nilenso/winter-onboarding-2021 pull request #51
Opened 2021-12-23 13:03 UTC by alishamohanty

Generalise the structure of hiccup form. 
Given inputs and attributes for the form, it will generate hiccup form.

2021-12-27 11:51 UTC, shhivam approved these changes

2021-12-27 11:51 UTC, shhivam commented on src/winter_onboarding_2021/fleet_management_service/views/cab.clj
> +                                                    :value "Delete"}]}))})])
Nice! I forgot about the form in the modal

2022-01-03 10:27 UTC, neenaoffline requested changes

2022-01-06 09:02 UTC, govindkrjoshi commented
Closing this PR since it was decided to not extract the form component yet

2022-01-06 09:02 UTC, closed without merging